import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/providers/query-provider";
import { Iceberg, Geist, Inter, Manrope } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

const brand = Iceberg({
  subsets: ["latin"],
  variable: "--font-brand",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Rentmart - Marketplace for Rural Area",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='h-full antialiased font-sans'>
      <body
        className={`${inter.className} ${manrope.variable} ${geist.variable} ${brand.variable} min-h-full flex flex-col`}
      >
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
